openapi: '3.0.3'
info:
  title: External backend service 1
  version: "0.0.1"
servers:
  - description: Remote
    url: "/external-backend-service1/"
  - description: Local
    url: "/"
paths:
  /test:
    get:
      responses:
        200:
          description: asdas
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/A"

components:
  schemas:
    A:
      type: object
      properties:
        service1Prop: 
          type: string

